hvdsa/urls.py
from django.contrib.gis import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('turfcutter/', include('turfcutter.urls')),
    path('', RedirectView.as_view(url='turfcutter/', permanent=False),
        name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
]

turfcutter/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView
from .models import Parcel
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('canvass-pdf/<int:canvass_id>/', canvass_pdf, name='canvass-pdf'),
    path('new-canvass/<int:campaign_id>/', new_canvass, name='new-canvass'),
    path('new-campaign', new_campaign, name='new-campaign'),
    path('new-canvasser', new_canvasser, name='new-canvasser'),
    path('campaign-details/<int:campaign_id>/', campaign_details, name='campaign-details'),
    path('canvass-details/<int:canvass_id>/', canvass_details, name='canvass-details'),
    path('canvasser-details/<int:canvasser_id>/', canvasser_details, name='canvasser-details'),
    path('canvass-area/<int:canvass_id>/', canvass_area_define, name='canvass-area'),
    path('turf/<int:canvass_id>/', turf_define, name='turf'),
    path('campaigns/', CampaignListView.as_view(), name='campaigns'),
    path('canvasses/', CanvassListView.as_view(), name='canvasses'),
    path('canvassers/', CanvasserListView.as_view(), name='canvassers'),
    path('turf-selection/<int:canvass_id>/', turf_select, name='turf-selection'),
    path('turf-canvass/<int:turf_id>/', turf_canvass, name='turf-canvass'),
    path('interaction/<int:turf_id>/<int:parcel_id>/', new_interaction, name='interaction'),
    path('turf-interactions/<int:turf_id>/', turf_interactions, name='turf-interactions'),
    re_path(r'^data/(?P<z>\d+)/(?P<x>\d+)/(?P<y>\d+).geojson$',
        UntrimmedTiledGeoJSONLayerView.as_view(model=Parcel),
        name='data_tiled'),
]

turfcutter/models.py
from django.contrib.postgres.fields import JSONField
from django.contrib.gis.db import models
from django.contrib.auth.models import User
from datetime import date


class Campaign(models.Model):
    owner = models.ForeignKey(User, on_delete=models.PROTECT)
    name = models.CharField(max_length=140)
    start_date = models.DateField(default=date.today)
    end_date = models.DateField(default=date.today)
    description = models.TextField(blank=True)

    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return '/campaign-details/%d/' % self.id


class Canvasser(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=15)
    email = models.EmailField()

    def __str__(self):
        return '%s, %s' % (self.last_name, self.first_name)

    def get_absolute_url(self):
        return '/canvasser-details/%d/' % self.id


class Canvass(models.Model):
    owner = models.ForeignKey(User, on_delete=models.PROTECT)
    name = models.CharField(max_length=140)
    date = models.DateField(default=date.today)
    description = models.TextField(blank=True)
    canvassers = models.ManyToManyField(Canvasser)
    campaign = models.ForeignKey(Campaign, on_delete=models.PROTECT)

    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return '/canvass-details/%d/' % self.id


class CanvassArea(models.Model):
    canvass = models.OneToOneField(Canvass,
        on_delete=models.CASCADE, primary_key=True)
    geom = models.PolygonField(srid=4326)

    def __str__(self):
        return '%s Area' % self.canvass.name


class Turf(models.Model):
    canvass = models.ForeignKey(Canvass, on_delete=models.CASCADE)
    canvassers = models.ManyToManyField(Canvasser, blank=True)
    name = models.CharField(max_length=140)
    geom = models.PolygonField(srid=4326)

    def __str__(self):
        return '%s Turf %s' % (self.canvass.name, self.name)

    def get_absolute_url(self):
        return '/turf-canvass/%d/' % self.id


class CensusTract(models.Model):
    gid = models.AutoField(primary_key=True)
    statefp = models.CharField(max_length=2, blank=True, null=True)
    countyfp = models.CharField(max_length=3, blank=True, null=True)
    tractce = models.CharField(max_length=6, blank=True, null=True)
    geoid = models.CharField(max_length=11, blank=True, null=True)
    name = models.CharField(max_length=7, blank=True, null=True)
    namelsad = models.CharField(max_length=20, blank=True, null=True)
    mtfcc = models.CharField(max_length=5, blank=True, null=True)
    funcstat = models.CharField(max_length=1, blank=True, null=True)
    aland = models.DecimalField(max_digits=65535,
        decimal_places=65535, blank=True, null=True)
    awater = models.DecimalField(max_digits=65535,
        decimal_places=65535, blank=True, null=True)
    intptlat = models.CharField(max_length=11, blank=True, null=True)
    intptlon = models.CharField(max_length=12, blank=True, null=True)
    geom = models.MultiPolygonField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'census_tract'

    def __str__(self):
        return '%s' % self.name


class CongressionalDistrict(models.Model):
    gid = models.AutoField(primary_key=True)
    statefp = models.CharField(max_length=2, blank=True, null=True)
    cd115fp = models.CharField(max_length=2, blank=True, null=True)
    affgeoid = models.CharField(max_length=13, blank=True, null=True)
    geoid = models.CharField(max_length=4, blank=True, null=True)
    lsad = models.CharField(max_length=2, blank=True, null=True)
    cdsessn = models.CharField(max_length=3, blank=True, null=True)
    aland = models.FloatField(blank=True, null=True)
    awater = models.FloatField(blank=True, null=True)
    geom = models.MultiPolygonField(srid=4269, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'congressional_district'

    def __str__(self):
        return 'District %s' % self.cd115fp


class County(models.Model):
    gid = models.AutoField(primary_key=True)
    statefp = models.CharField(max_length=2, blank=True, null=True)
    countyfp = models.CharField(max_length=3, blank=True, null=True)
    countyns = models.CharField(max_length=8, blank=True, null=True)
    affgeoid = models.CharField(max_length=14, blank=True, null=True)
    geoid = models.CharField(max_length=5, blank=True, null=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    lsad = models.CharField(max_length=2, blank=True, null=True)
    aland = models.FloatField(blank=True, null=True)
    awater = models.FloatField(blank=True, null=True)
    geom = models.MultiPolygonField(srid=4269, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'county'

    def __str__(self):
        return '%s County' % self.name


class Parcel(models.Model):
    short_pin = models.CharField(max_length=100, blank=True, null=True)
    zoning = models.CharField(max_length=100, blank=True, null=True)
    pre_percent = models.DecimalField(max_digits=65535,
        decimal_places=65535, blank=True, null=True)
    pre_value = models.DecimalField(max_digits=65535,
        decimal_places=65535, blank=True, null=True)
    eq_value = models.DecimalField(max_digits=65535,
        decimal_places=65535, blank=True, null=True)
    tent_value = models.DecimalField(max_digits=65535,
        decimal_places=65535, blank=True, null=True)
    acreage_of_parent = models.DecimalField(max_digits=65535,
        decimal_places=65535, blank=True, null=True)
    assessed_value = models.DecimalField(max_digits=65535,
        decimal_places=65535, blank=True, null=True)
    building_assessment = models.DecimalField(max_digits=65535,
        decimal_places=65535, blank=True, null=True)
    capped_value = models.DecimalField(max_digits=65535,
        decimal_places=65535, blank=True, null=True)
    cvt_code = models.CharField(max_length=10, blank=True, null=True)
    cvt_description = models.CharField(max_length=40, blank=True, null=True)
    historical_district = models.CharField(max_length=4, blank=True, null=True)
    homestead_taxable = models.DecimalField(max_digits=65535,
        decimal_places=65535, blank=True, null=True)
    homestead_percent = models.DecimalField(max_digits=65535,
        decimal_places=65535, blank=True, null=True)
    lastupdate = models.DecimalField(max_digits=65535,
        decimal_places=65535, blank=True, null=True)
    legal_description = models.TextField(blank=True, null=True)
    owner_care_of = models.CharField(max_length=100, blank=True, null=True)
    owner_city = models.CharField(max_length=100, blank=True, null=True)
    owner_country = models.CharField(max_length=100, blank=True, null=True)
    owner_name = models.CharField(max_length=100, blank=True, null=True)
    owner_name2 = models.CharField(max_length=100, blank=True, null=True)
    owner_state = models.CharField(max_length=2, blank=True, null=True)
    owner_street = models.CharField(max_length=100, blank=True, null=True)
    owner_zip = models.CharField(max_length=20, blank=True, null=True)
    parent_parcel_num = models.CharField(max_length=40, blank=True, null=True)
    pin = models.CharField(max_length=40, blank=True, null=True)
    prop_city = models.CharField(max_length=100, blank=True, null=True)
    prop_class = models.CharField(max_length=10, blank=True, null=True)
    prop_class_description = models.CharField(max_length=100,
        blank=True, null=True)
    prop_state = models.CharField(max_length=2, blank=True, null=True)
    prop_street = models.CharField(max_length=100, blank=True, null=True)
    prop_street_num = models.DecimalField(max_digits=65535,
        decimal_places=65535, blank=True, null=True)
    prop_zip = models.CharField(max_length=20, blank=True, null=True)
    school_district = models.CharField(max_length=100, blank=True, null=True)
    school_name = models.CharField(max_length=100, blank=True, null=True)
    sev = models.DecimalField(max_digits=65535,
        decimal_places=65535, blank=True, null=True)
    shape_area = models.DecimalField(max_digits=65535,
        decimal_places=65535, blank=True, null=True)
    shape_len = models.DecimalField(max_digits=65535,
        decimal_places=65535, blank=True, null=True)
    stated_area = models.CharField(max_length=20, blank=True, null=True)
    status_code = models.CharField(max_length=4, blank=True, null=True)
    status_desc = models.CharField(max_length=20, blank=True, null=True)
    taxable_value = models.DecimalField(max_digits=65535,
        decimal_places=65535, blank=True, null=True)
    txpyrs_care_of = models.CharField(max_length=100, blank=True, null=True)
    txpyrs_city = models.CharField(max_length=100, blank=True, null=True)
    txpyrs_country = models.CharField(max_length=100, blank=True, null=True)
    txpyrs_name = models.CharField(max_length=100, blank=True, null=True)
    txpyrs_state = models.CharField(max_length=100, blank=True, null=True)
    txpyrs_street_addr = models.CharField(max_length=100, blank=True, null=True)
    txpyrs_zip_code = models.CharField(max_length=20, blank=True, null=True)
    unit_apt_num = models.CharField(max_length=20, blank=True, null=True)
    geometry = models.TextField(blank=True, null=True)
    geom = models.MultiPolygonField(srid=4326, blank=True, null=True)
    centroid = models.PointField()
    lon_centroid = models.DecimalField(max_digits=65535,
        decimal_places=65535, blank=True, null=True)
    lat_centroid = models.DecimalField(max_digits=65535,
        decimal_places=65535, blank=True, null=True)
    county_gid = models.IntegerField(blank=True, null=True)
    cd_gid = models.IntegerField(blank=True, null=True)
    ct_gid = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'parcel'

    def __str__(self):

turfcutter/forms.py
from django import forms
from django.forms import ModelForm, formset_factory
from leaflet.forms.widgets import LeafletWidget
from .models import *


# https://stackoverflow.com/a/44224563
class HorizontalRadioSelect(forms.RadioSelect):
    template_name = 'turfcutter/horizontal_select.html'


class DateInput(forms.DateInput):
    input_type = 'date'


class NewCampaignForm(ModelForm):
    class Meta:
        model = Campaign
        fields = ['name', 'start_date', 'end_date']
        widgets = {'start_date': DateInput(), 'end_date': DateInput()}


class NewCanvassForm(ModelForm):
    class Meta:
        model = Canvass
        fields = ['name', 'date']
        widgets = {
            'date': DateInput()
        }


class NewCanvasserForm(ModelForm):
    class Meta:
        model = Canvasser
        fields = ['first_name', 'last_name', 'email', 'phone_number']


class CanvassAreaForm(ModelForm):
    class Meta:
        model = CanvassArea
        fields = ('geom',)
        widgets = {'geom': LeafletWidget()}


class TurfForm(ModelForm):
    class Meta:
        model = Turf
        fields = ('geom',)
        widgets = {'geom': LeafletWidget()}


class InteractionForm(ModelForm):
    class Meta:
        model = Interaction
        fields = ('at_home', 'accepted_material', 'campaign_response',
            'dsa_response', 'notes')
        widgets = {'at_home': HorizontalRadioSelect, 'accepted_material': HorizontalRadioSelect,
                'campaign_response': HorizontalRadioSelect, 'dsa_response': HorizontalRadioSelect}
        labels= {'at_home': 'Home', 'accepted_material': 'Accept', 'campaign_response': 'Campaign', 'dsa_response': 'DSA'}

class InlineInteractionForm(ModelForm):
    class Meta:
        model = Interaction
        fields = ('at_home', 'accepted_material', 'campaign_response',
            'dsa_response', 'notes')
        widgets = {'at_home': HorizontalRadioSelect, 'accepted_material': HorizontalRadioSelect,
                'campaign_response': HorizontalRadioSelect, 'dsa_response': HorizontalRadioSelect,
                'notes': forms.Textarea(attrs={'rows': 1})}
        labels= {'at_home': 'Home', 'accepted_material': 'Accept', 'campaign_response': 'Campaign', 'dsa_response': 'DSA'}

turfcutter/templates/turfcutter/base.html
<!DOCTYPE html>
<html lang="en">
  <head>

    {% block title %}<title>HVDSA TurfCutter</title>{% endblock %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static '/turfcutter/css/styles.css' %}">
  </head>

  <body>
    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <style>body { padding-top: 70px; }</style>



    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          {% if user.is_authenticated %}
          <a class="navbar-brand" href="#">HVDSA TurfCutter</a>
          {% endif %}
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'campaigns' %}">Campaigns</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
             {% if user.is_authenticated %}
              <li><p class="navbar-text">User: {{ user.get_username }}</p></li>
              <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
            {% else %}
              <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
            {% endif %}
          </ul>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>
      {% if user.is_authenticated %}
      {% block content %}{% endblock %}
      {% endif %}
      {% block login_content %}{% endblock %}
  </body>
</html>

turfcutter/templates/turfcutter/campaign_details.html
{% extends "turfcutter/base.html" %}

{% block content %}
<div class='panel panel-primary'>
  <div class='panel-heading'>
    <h1 class='panel-title'>{{ campaign.name }}</h1>
  </div>
  <div class='panel-body'>
    <p>{{campaign.description}}</p>
    <ul>
      {% for canvass in canvass_list %}
      <li>
        <a href="/turfcutter{{ canvass.get_absolute_url }}">{{ canvass.name }}</a>
      </li>
      {% endfor %}
    </ul>
    <a id='canvass_button' class="btn btn-primary" href="{% url 'new-canvass' campaign_id=campaign.id %}">New Canvass</a>
  </div>
</div>
{% endblock %}

turfcutter/templates/turfcutter/canvas_details.html
{% extends "turfcutter/base.html" %}

{% block title %}
<title> Canvas Details </title>
{% load leaflet_tags %}
{% leaflet_js %}
{% leaflet_css %}
<script type="text/javascript">
function map_init_canvas_area (map, options){
    var style = {
      "stroke": true,
      "weight": 2,
      "color": "#666666",
      "fillColor": "#ff0000",
      "opacity": 0.8,
      "fillOpacity": 0.4,
    };
    var polygon = L.geoJSON({% autoescape off %}{{ canvas_area.geom.json }}{% endautoescape %}, style).addTo(map);
    map.fitBounds(polygon.getBounds());
    map.dragging.disable();
    map.touchZoom.disable();
    map.doubleClickZoom.disable();
    map.scrollWheelZoom.disable();
    map.boxZoom.disable();
    map.keyboard.disable();
    if (map.tap) map.tap.disable();
}
</script>
<style>
.leaflet-container-default {
    max-width: 70%;
    margin-left: 30%;
}
.detail-subpanel {
    position: absolute;
    left: 0px;
    width: 30%;
    max-height: 85%;
    overflow-y: scroll;
    overflow-x: hidden;
}
.panel {
    position: relative;
}
</style>
{% endblock %}
    

{% block content %}
<div class='panel-group'>
<div class='panel panel-primary'>
    <div class='panel-heading'>
        <h1 class='panel-title'>
            <a data-toggle='collapse' href='#collapse1'>{{ canvas.name }}</a>
        </h1>
    </div>
    <div id='collapse1' class='panel-collapse collapse in'>
        <div class='detail-subpanel'>
        <p>{{ canvas.description }}</p>
        <p>{{ canvas.date }}</p>
        <a id='pdf_button' class="btn btn-primary" href="{% url 'canvas-pdf' canvas_id=canvas.id %}">Generate Turf Sheets</a>

        </div>
        {% leaflet_map "area_map" callback="window.map_init_canvas_area" %}
    </div>
</div>
{% for turf_id, turf_info in turf_info_dict.items %}
<div class='panel panel-default'>
    <div class='panel-heading'>
        <h1 class='panel-title'>
            <a data-toggle='collapse' href='#collapse{{turf_id}}'>
                {{ turf_info.turf.name }}
            </a>
        </h1>
    </div>
    <div id='collapse{{turf_id}}' class='panel-collapse collapse in'>
        <div class='detail-subpanel'>
        <ul>
        {% for parcel in turf_info.parcels %}
          <li>{{ parcel.prop_street_num }} {{parcel.prop_street}}</li>
        {% endfor %}
        </ul>
        </div>
        <div id="turf-map-{{ turf_info.turf.id }}" class="leaflet-container-default"></div>
    <script type="text/javascript">
(function () {
  function loadmap() {
    var djoptions = {"srid": null, "extent": [[-90, -180], [90, 180]], "fitextent": true, "center": [42.24, -83.61], "zoom": 15, "minzoom": 9, "maxzoom": 18, "layers": [["OSM", "http://mt0.google.com/vt/lyrs=y&hl=en&x={x}&y={y}&z={z}&s=Ga", "\u00a9 <a href=\"http://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors"]], "overlays": [], "attributionprefix": null, "scale": "metric", "minimap": false, "resetview": false, "tilesextent": []},
    options = {djoptions: djoptions, initfunc: loadmap,
    globals: false, callback: null},
    map = L.Map.djangoMap('turf-map-{{ turf_info.turf.id }}', options);
     var style = {
      "stroke": true,
      "weight": 2,
      "color": "#666666",
      "fillColor": "#ff0000",
      "opacity": 0.8,
      "fillOpacity": 0.4,
    };
    var polygon = L.geoJSON({% autoescape off %}{{ turf_info.turf.geom.json }}{% endautoescape %}, style).addTo(map);
    map.fitBounds(polygon.getBounds());
    map.dragging.disable();
    map.touchZoom.disable();
    map.doubleClickZoom.disable();
    map.scrollWheelZoom.disable();
    map.boxZoom.disable();
    map.keyboard.disable();
    if (map.tap) map.tap.disable();
 }
  var loadevents = ["load"];
  if (loadevents.length === 0) loadmap();
  else if (window.addEventListener) for (var i=0; i<loadevents.length; i++) window.addEventListener(loadevents[i], loadmap, false);
  else if (window.jQuery) jQuery(window).on(loadevents.join(' '), loadmap);
})();
</script>
    </div>
</div>
{% endfor %}
</div>
{% endblock %}

turfcutter/templates/turfcutter/canvass_area.html
<style>
.leaflet-container {  /* all maps */
  width:  100%;
  height: 100%;
  z-index: 1;
}
label[for="id_geom"] { display:none; }
#submit_area {
  position: absolute;
  top: 12;
  right: 12;
  z-index: 10;
  width: 200;
  height: 40;
  background-color: #36e24a;
  font-size: 16;
  border-radius: 12px;
}
#button-outline {
  position: absolute;
  top: 0;
  right: 0;
  z-index: 5;
  width: 220;
  height: 60;
  border-radius: 0px 0px 0px 20px;
  background-color: #FFFFFF;
}
#instructions {
  font-weight: bold;
  position: absolute;
  text-align: center;
  line-height: 60px;
  top: 0;
  right: 40%;
  z-index: 5;
  width: 20%;
  height: 60;
  background-color: #FFFFFF;
  border-radius: 0px 0px 20px 20px;
}
</style>
{% load leaflet_tags %}
<html>
  <head>
   {% leaflet_js plugins="forms" %}
   {% leaflet_css plugins="forms" %}
  </head>
  <body>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <div id='button-outline'></div>
        <div id='instructions'>Draw the total area you wish to canvass.</div>
        <input type="submit" value="Complete" id='submit_area'/>
    </form>
  </body>
</html>

turfcutter/templates/turfcutter/canvasser_details.html
{% extends "turfcutter/base.html" %}

{% block content %}
<div class='panel panel-primary'>
    <div class='panel-heading'>
        <h1 class='panel-title'>{{ canvasser.last_name }}</h1>
    </div>
    <div class='panel-body'>
      </p>{{ canvasser.first_name }} {{ canvasser.last_name }} | {{ canvasser.phone_number }} | {{ canvasser.email }}</p>
    </div>
</div>
{% endblock %}

turfcutter/templates/turfcutter/index.html
{% extends "turfcutter/base.html" %}

{% block content %}

<style>
#id_name { width: 20em; }
#id_description { width: 20em; }
</style>

<div class='jumbotron'>
    <div class=row>
        <div class='col-md-4 col-md-offset-4 text-center'>
          <h2> Active Campaigns </h2>
          <ul>
            {% for campaign in campaign_list %}
            <li>
              <a href="/turfcutter{{ campaign.get_absolute_url }}">{{ campaign.name }}</a>
            </li>
            {% endfor %}
          </ul>
          <a id='campaign_button' class="btn btn-primary" href="{% url 'new-campaign' %}">New Campaign</a>
        </div>
    </div>
</div>
{% endblock %}

turfcutter/templates/turfcutter/new_canvas.html
{% extends "turfcutter/base.html" %}

{% block content %}

<style>
#id_name { width: 20em; }
#id_description { width: 20em; }
</style>

<div class='jumbotron'>
    <div class=row>
        <div class='col-md-4 col-md-offset-4 text-center'>
            <h2>Start a New Canvas</h2>
            <form action="" method="post">
                {% csrf_token %}
                <table>
                    {{ form }}
                </table>
                <input type="submit" value="Submit" />
            </form>
        </div>
    </div>
</div>
{% endblock %}

turfcutter/templates/turfcutter/new_canvass.html
{% extends "turfcutter/base.html" %}

{% block content %}

<style>
#id_name { width: 20em; }
#id_description { width: 20em; }
</style>

<div class='jumbotron'>
    <div class=row>
        <div class='col-md-4 col-md-offset-4 text-center'>
            <h2>Start a New Canvass</h2>
            <form action="" method="post">
                {% csrf_token %}
                <table>
                    {{ form }}
                </table>
                <input type="submit" value="Submit" />
            </form>
        </div>
    </div>
</div>
{% endblock %}

turfcutter/templates/turfcutter/new_canvasser.html
{% extends "turfcutter/base.html" %}

{% block content %}

<style>
#id_name { width: 20em; }
#id_description { width: 20em; }
</style>

<div class='jumbotron'>
    <div class=row>
        <div class='col-md-4 col-md-offset-4 text-center'>
            <h2>Add a New Canvasser</h2>
            <form action="" method="post">
                {% csrf_token %}
                <table>
                    {{ form }}
                </table>
                <input type="submit" value="Submit" />
            </form>
        </div>
    </div>
</div>
{% endblock %}

turfcutter/templates/turfcutter/turf_canvass.html
{% extends "turfcutter/base.html" %}

{% block content %}
<div class='panel panel-primary'>
  <div class='panel-heading'>
    <h1 class='panel-title'>{{ canvass.name }} Turf {{ turf.name }}</h1>
  </div>
  <div class='panel-body'>
    {% if parcel_list %}
    <ul>
      {% for parcel in parcel_list %}
      <li>
          <a href="/turfcutter/interaction/{{ turf.id }}/{{parcel.id}}/">{{ parcel.prop_street_num }} {{parcel.prop_street}}</a>
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <p>No parcels in this turf.</p>
    {% endif %}
  </div>
</div>
{% endblock %}

turfcutter/templates/turfcutter/turf_interactions.html
{% extends "turfcutter/base.html" %}

<!- https://www.djangosnippets.org/snippets/1442/ ->
{% block content %}
<div class='panel panel-primary'>
    <div class='panel-heading'>
	<h1 class='panel-title'>{{ turf.canvass.name }} Turf {{ turf.name }}</h1>
    </div>
    <div class='panel-body'>
        {{ formset.management_form }}
	{{ formset.non_form_errors.as_ul }}
	<table id="formset" class="form">
	    {% for form in formset.forms %}
	    {% if forloop.first %}
	    <thead><tr>
		    {% for field in form.visible_fields %}
		    <th>{{ field.label|capfirst }}</th>
		    {% endfor %}
		</tr></thead>
		{% endif %}
		<tr class='row1'>
		    {% for field in form.visible_fields %}
		    <td>
			{% if forloop.first %}
			{% for hidden in form.hidden_fields %}
			{{ hidden }}
			{% endfor %}
			{% endif %}
			{{ field.errors.as_ul }}
			{{ field }}
		    </td>
		    {% endfor %}
		</tr>
		{% endfor %}
	</table>
    </div>
</div>
{% endblock %}